version: "3.9"
services:
  db:
    image: mysql:8.4
    env_file: .env
    ports: ["3306:3306"]
    volumes: [db_data:/var/lib/mysql]
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      retries: 5
  api:
    build: .
    env_file: .env
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
