spring:
  profiles:
    active: dev
  application:
    name: pies_yoga
  config.import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/piesdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}

logging.level.org.hibernate.SQL: debug
